### ISSUE TITLE
报错问题请教

### ISSUE THREAD

**Issue by Madokadaisuki** [rikakomoe/cqhttp-twitter-bot#5]
[ERROR] twitter - unhandled error on fetching tweets for https://twitter.com/NANRI_SHIN: {"errno":"ETIMEDOUT","code":"ETIMEDOUT","syscall":"connect","address":"104.244.42.194","port":443}
运行时会提示上述文字，我仔细看了443端口也没有显示占用，全局代理也已经打开，并且无法完成对推特的转发，请问这应该如何处理？

**Comment by satouriko** [comment]
设法检查一下你的代理有没有用上 看起来并没有

**Comment by Madokadaisuki** [comment]
[ERROR] twitter - unhandled error on fetching tweets for https://twitter.com/NANRI_SHIN: {"code":"ECONNRESET","path":null,"host":"api.twitter.com","port":443}
进行更高级的全局代理以后报错信息则变成了这个，这个又应该怎么处理？
